### PR TITLE
improve readability in zh

### PR DESCRIPTION
**Pull request by aidewoode**
For the readability, I add space between the Chinese and English letter. And I also change some translation to make it easier to understand. Now I just finished the first chapter, and the rest chapter I will do it later.

### CODE REVIEW

**Comment by braydie** [comment]
hey @aidewoode thanks for the contribution! based on some of the feedback in another issue we've had around translations, before merging in I'd like to get a second set of eyes to review the changes you've made (as I can't verify them myself, unfortunately!)

@ahangchen wrote the original translation so they'd be the best person to review I believe

**Comment by ahangchen** [comment]
@aidewoode For fixes of Chinese version,  please open a pull request into this repository https://github.com/ahangchen/HowToBeAProgrammer.

**Comment by aidewoode** [comment]
@ahangchen Is there any difference between the two repository, why I should pull another same request to a fork repository?

**Comment by ahangchen** [comment]
@aidewoode Because Braydie can't review it without understanding Chinese, and this [repository](https://github.com/ahangchen/HowToBeAProgrammer) is the original translation for Chinese, so I will help to review fixes for Chinese version and finally push them to this repository.

**Comment by aidewoode** [comment]
yeah, I get it, but I think maybe it's not a good idea. Because, first, we have to merge twice for the same purpose, it's seem less efficient. And second, imagine this, when we have others translation version, like Spanish, Japanese or some thing else in the later , and a contributor want to translate some to Chinese, and also want to translate some to Japanese, maybe he also want to change some original English content. If we have fork repository for each translation version, he have to fork at least three repository, and separate one commit to three for the each repository, I think this will made him so sad. 

I think in this repository you can review Chinese too, When have some Chinese translation contribution, I think @braydie will mention you, and you can mention others Chinese contributor to review this commit together. I think just contribute to one repository will be simpler.

**Comment by ahangchen** [comment]
Contributing to one repository is actually simpler for the contributor, but not for the manager. Solving problems in the corresponding branch is why git is charming. Although we have to merge twice, it's clearer.

**Comment by aidewoode** [comment]
@ahangchen all right, I will push another quest , and this PR will be closed

**Comment by braydie** [comment]
I agree with both of you on this - it makes sense to have a single repository for ease of contribution but is difficult to manage, particularly as it is just me at the moment. Perhaps the solution to this would be making the person who makes the initial contribution of a translation an official contributor for this project, that way they can manage pull requests that come through for 'their' language

**Pull request closed without merging**
