### PR TITLE
"inured" is not very accessible; "used" is clearer

### PR DESCRIPTION
**Pull request by waldyrious**
especially for non-native speakers. I believe the meaning is preserved appropriately with this change.

### CODE REVIEW

**Comment by braydie** [comment]
Hey @waldyrious, I agree 'inured' is a bit tricky (had to google it myself!), but I'm not sure that 'used' conveys the same meaning in this instance

**Comment by waldyrious** [comment]
I believe it preserves the original meaning well enough (though not exactly, true). Maybe someone can come up with a better alternative :)

**Comment by Socialery** [comment]
"accustomed to" is a bit more accessible, "comfortable with" is a lot more accessible, but a tad far away from the meaning, "revels in" has a completely different meaning, but in context, has similar intent! *(I don't know about how accessible "revels" is though)*

**Comment by waldyrious** [comment]
@Socialery from the options you propose, It seems to me that "accustomed to" is the one that most closely matches the original intent. And it is an improvement (in terms of accessibility) over "inured to", so :+1: from me.

**Comment by braydie** [comment]
Yes, "accustomed to" gets a vote from me too

**Comment by waldyrious** [comment]
okay, updated the PR with the new proposed wording :)

**Pull request merged**
