### PR TITLE
fix word

### PR DESCRIPTION
**Pull request by tianheg**

### CODE REVIEW

**Comment by braydie** [comment]
Thanks for contributing @tianheg! I can't read Chinese so will have to refer to @ahangchen who has approved contributions to the Chinese translation in the past

**Comment by tianheg** [comment]
Hello, seems @ahangchen busy for others. You could see this [DeepL](https://www.deepl.com/translator#en/zh/How%20to%20Debug%20Using%20a%20Log). It's just a extra Chinese word

**Comment by ahangchen** [comment]
Sorry for my late response. I have review the change and comfirm the fix for my typo.

**Comment by tianheg** [comment]
@ahangchen It's OK. I could understand you.

**Pull request merged**
