### PR TITLE
Update 04-How to Stress Test.md

### PR DESCRIPTION
**Pull request by rs38**
.... may be worth to differ even more and mentioning tools, devops etc.

(stress testing is no fun :) )

### CODE REVIEW

**Comment by rs38** [comment]
no one?

**Comment by braydie** [comment]
Hey @rs38 sorry to not have gotten back to you sooner! Let me take a look over this change and get back to you :+1:

**Comment by braydie** [comment]
hey @rs38, I've taken a look at your changes and I'm not 100% convinced it adds much to the section as it mostly repeats some of what is said a couple of paragraphs later. I would be keen to certainly add the terms "load test" and "performance test" into the original version of the page. I think probably around the second and third paragraph?

**Comment by rs38** [comment]
I’m an IT pro doing load & perf testing for a living and I just start to explore the world of github and open source projects even if „only“ documentation or education. 

It was a very early and tiny try to help or be part of this community with my experience, but the reaction time for comments to contributions is too long for me to get the feeling it makes sense for me and having some fun to spend my knowledge.

 

 

 

Von: Braydie Grove [mailto:notifications@github.com] 
Gesendet: Sonntag, 28. Februar 2016 09:34
An: braydie/HowToBeAProgrammer <HowToBeAProgrammer@noreply.github.com>
Cc: rs38 <fbethke@gmx.de>
Betreff: Re: [HowToBeAProgrammer] Update 04-How to Stress Test.md (#60)

 

hey @rs38 <https://github.com/rs38> , I've taken a look at your changes and I'm not 100% convinced it adds much to the section as it mostly repeats some of what is said a couple of paragraphs later. I would be keen to certainly add the terms "load test" and "performance test" into the original version of the page. I think probably around the second and third paragraph?

**Comment by braydie** [comment]
I can only apologize for not getting back to you sooner, but unfortunately
this is one of the realities of making contributions to open source as we
all have day jobs and other commitments.

Given your background it would be great to get your input on this section
in particular. Would you update your pull request to include some more
about tools and techniques used in stress testing?

**Pull request closed without merging**
