### PR TITLE
Adds link to physical version of book

### PR DESCRIPTION
**Pull request by calvin-evans**
I turned this into a book on Blurb. The profit margin is set at 0 so I wouldn't get anything - the price would be paid directly to Blurb for the cost of manufacturing and shipping the book.

### CODE REVIEW

**Comment by braydie** [comment]
hey @calvin-evans, thanks for the pull request. It would be awesome to have a physical copy of the book, but I'm not sure it would necessarily work - the book is more of a living document and will undoubtedly see changes regularly - I'd be sad to see someone purchase a copy of the book and for it to become 'obsolete' soon after making changes to this repository. 

I wonder if there is much demand for a physical copy? 

Maybe we need to look at doing a complete versioning of the book to enable this sort of thing - planning versions, and only allowing changes to be go into the 'published' version periodically?

**Comment by braydie** [comment]
Or are people happy to having changes 'published' and available immediately? I kind of like this approach as it means changes and improvements can be used straight away

**Comment by calvin-evans** [comment]
Hey @braydie I wrestled with the same problem. In terms of demand, I've bought two copies for myself which was my original motivation for compiling the book version. I tend to read this sort of stuff when I'm not near a screen and able to work on projects and things so it's nice to have a physical copy. 

It took me about 2 hours give or take to convert the .md files to .rtf, make sure they were arranged correctly in the editor and number the contents page which was a little bit of a pain so I thought I'd share the finished result with anyone else who wanted to do the same. If people don't think it's a good idea to have a link featured so prominently (which I totally get) that's fine I just couldn't think of anywhere else to put it where people who were interested in an, even slightly outdated, physical copy of the book would see it.

Regarding the "living document" point, I'd be happy to keep creating new editions as it wouldn't be a big job - I'd also be happy to share the account credentials with other people wanted to help if anyone was interested. Perhaps we could use releases as a way of marking "editions" for the physical book?

**Comment by braydie** [comment]
I can appreciate having time away from the screen, and there's not much that beats flicking through a physical book! 

I guess now that the initial conversion into RTF has been done that should mean that there is unlikely to be another big chunk of two hours work with regards to updating it and stuff. I'm happy to include the link where you've put it as it sits in line with the gitbook stuff. 

I think what I'd be keen to do would be to keep the online version always updating and not versioned as a whole (like first edition, etc), and have periodic updates to the physical copy - probably including a date for when the edition was created and providing a link back to this repository on the blurb page if possible (so that people can see the latest version if they want). 

I'd rather make the changes immediately available to everyone online than (almost) arbitrarily hold back changes until a new edition is ready for the sake of a physical copy.

**Comment by braydie** [comment]
Could you include something like this after the link:

> First edition, created on //DATE//

**Comment by calvin-evans** [comment]
Yeah no probs I'll just collate new content into a new edition every week or when there's any quite large changes. 

On a side not, if anyone wants access to the blurb account just message me.

**Comment by braydie** [comment]
Awesome :+1: 

May have to order a copy myself :)

Also, Robert is missing a 't' on the front cover

I may start looking into getting a proper cover created (it can be used on the gitbook edition too!)

**Comment by calvin-evans** [comment]
Crap, can't fix until Monday as I did it at the office :cry: Can you hang fire on merging until then? 

I'll give it a once over monday morning (GMT) and fix that and any other formatting issues I spot.

**Comment by braydie** [comment]
Not a problem, I'll hold tight till then :)

**Comment by calvin-evans** [comment]
@braydie updated the link to the new version of the book. Should be good to go

**Comment by braydie** [comment]
Hey @calvin-evans, could you adjust the year published - just noticed that it's 2017 :smile:

**Comment by calvin-evans** [comment]
*Sigh* been doing that all year

**Pull request merged**
